version: '3.9'
services: 
  1-change-data-capture-monolith:
    image: 1_change_data_capture_monolith
    container_name: '1_change_data_capture_monolith'
    restart: on-failure
    build: 
      context: ./1_change_data_capture_monolith
      dockerfile: ./Dockerfile
    ports: 
      - 8080:8080
    environment:
      - DATABASE_HOST=postgres-monolith-database
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASS=password
      - DATABASE_DB=monolith-db
    depends_on: 
      - postgres-monolith-database
    networks:
      - app-network

  postgres-monolith-database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=monolith-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge