version: '3.9'
services: 

  nginx-load-balancer:
    image: nginx:1.21.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx_50_50.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge