version: '3.9'
services: 

  nginx-load-balancer:
    image: nginx:1.21.3
    ports:
      - "80:80"
    volumes:
      - ./1_config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - 1-strangler-fig-monolith
    networks:
      - app-network

networks:
  app-network:
    external: false