version: '3.9'
services: 
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
    - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config_2:/etc/nginx/vhost.d:ro
    environment:
      - ENABLE_IPV6=true
      - DEFAULT_HOST=payment.service
    networks:
      - app-network

  2-strangler-fig-monolith:
    image: 2_strangler_fig_monolith
    container_name: '2_strangler_fig_monolith'
    restart: on-failure
    build: 
      context: ./2_strangler_fig_monolith
      dockerfile: ./Dockerfile
    ports: 
      - 8080:8080
    environment:
      - VIRTUAL_HOST=payment.service
      - VIRTUAL_PORT=8080
    networks:
      - app-network

  2-strangler-fig-inventory-ms:
    image: 2_strangler_fig_inventory_ms
    container_name: '2_strangler_fig_inventory_ms'
    restart: on-failure
    build: 
      context: ./2_strangler_fig_inventory_ms
      dockerfile: ./Dockerfile
    ports: 
      - 8081:8081
    environment:
      - VIRTUAL_HOST=payment.service
      - VIRTUAL_PORT=8081
    networks:
      - app-network

networks:
  app-network:
    external: false