version: '3.9'
services: 
  2-strangler-fig-monolith:
    image: 2_strangler_fig_monolith
    container_name: '2_strangler_fig_monolith'
    restart: on-failure
    build: 
      context: ./2_strangler_fig_monolith
      dockerfile: ./Dockerfile
    ports: 
      - 8080:8080
  2-strangler-fig-inventory_ms:
    image: 2_strangler_fig_inventory_ms
    container_name: '2_strangler_fig_inventory_ms'
    restart: on-failure
    build: 
      context: ./2_strangler_fig_inventory_ms
      dockerfile: ./Dockerfile
    ports: 
      - 8081:8081