version: '3.9'
services: 
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
    - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./3_config:/etc/nginx/vhost.d:ro
    environment:
      - ENABLE_IPV6=true
      - DEFAULT_HOST=payment.service
    networks:
      - app-network

networks:
  app-network:
    external: false