version: '3.9'
services: 

  nginx:
    image: nginx:1.21.3
    ports:
      - "80:80"
    volumes:
      - ./3_config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - 1-strangler-fig-monolith
      - 2-strangler-fig-inventory-ms
    networks:
      - app-network

networks:
  app-network:
    external: false