version: '3.9'
networks:
  app-network:
    external: true
services: 
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - ENABLE_IPV6=true
      - DEFAULT_HOST=whoami.local
    networks:
      - app-network
      
  1-strangler-fig-monolith:
    image: 1_strangler_fig_monolith
    container_name: '1_strangler_fig_monolith'
    restart: on-failure
    build: 
      context: ../Ejemplo_2/1_strangler_fig_monolith
      dockerfile: ./Dockerfile
    ports: 
      - 8080:8080
    networks:
      - app-network
    environment:
      - VIRTUAL_HOST=whoami.local
      - VIRTUAL_PORT=8080

#Docker Networks
#networks:
#  app-network:
#    driver: bridge