version: '3.9'
services: 
  2-strangler-fig-monolith:
    image: 2_strangler_fig_monolith
    container_name: '2_strangler_fig_monolith'
    restart: on-failure
    build: 
      context: ../Ejemplo_2/2_strangler_fig_monolith
      dockerfile: ./Dockerfile
    ports: 
      - 8080:8080
    networks:
      - appnetwork
  
  2-strangler-fig-payroll-ms:
    image: 2_strangler_fig_payroll_ms
    container_name: '2_strangler_fig_payroll_ms'
    restart: on-failure
    environment:
      MONOLITH_HOST: 2-strangler-fig-monolith
      MONOLITH_PORT: 8080
    build: 
      context: ../Ejemplo_2/2_strangler_fig_payroll_ms
      dockerfile: ./Dockerfile
    ports: 
      - 8081:8081
    depends_on: 
      - 2-strangler-fig-monolith
    networks:
      - appnetwork
networks:
  appnetwork:
    driver: bridge