version: '3.9'

services:
  strangler-fig-producer:
    image: strangler_fig_producer
    container_name: 'strangler_fig_producer'
    restart: on-failure
    build: 
      context: ./strangler_fig_producer
      dockerfile: ./Dockerfile
    ports: 
      - 9090:9090
    environment:
      - PAYROLL_TOPIC=payroll-all-msg-topic
      - INVOICING_TOPIC=invoicing-all-msg-topic
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - CONSUMER_GROUP_ID=payment-service-group
    networks:
      - app-network


networks:
  app-network:
    driver: bridge