version: '3.9'

services:

  1-strangler-fig-monolith:
    image: 1_strangler_fig_monolith
    container_name: '1_strangler_fig_monolith'
    restart: on-failure
    build: 
      context: ./1_strangler_fig_monolith
      dockerfile: ./Dockerfile
    ports: 
      - 8080:8080
    environment:
      - INVOICING_TOPIC=invoicing-topic
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - CONSUMER_GROUP_ID=payment-service-group
    networks:
      - app-network
  
  2-strangler-fig-payroll-ms:
    image: 2_strangler_fig_payroll_ms
    container_name: '2_strangler_fig_payroll_ms'
    restart: on-failure
    build: 
      context: ./2_strangler_fig_payroll_ms
      dockerfile: ./Dockerfile
    ports: 
      - 8081:8081
    depends_on: 
      - 1-strangler-fig-monolith
    environment:
      - MONOLITH_HOST=1-strangler-fig-monolith
      - MONOLITH_PORT=8080
      - PAYROLL_TOPIC=payroll-ms-topic
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - CONSUMER_GROUP_ID=payment-service-group
    networks:
      - app-network

  3-strangler-fig-cbr-ms:
    image: 3_strangler_fig_cbr
    container_name: '3_strangler_fig_cbr'
    restart: on-failure
    build: 
      context: ./3_strangler_fig_cbr
      dockerfile: ./Dockerfile
    ports: 
      - 8082:8082
    environment:
      - PAYROLL_CONSUMER_TOPIC=payroll-v2-topic
      - INVOICING_CONSUMER_TOPIC=invoicing-v2-topic
      - PAYROLL_PRODUCER_TOPIC=payroll-ms-topic
      - INVOICING_PRODUCER_TOPIC=invoicing-topic
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - CONSUMER_GROUP_ID=payment-service-group
    networks:
      - app-network

  strangler-fig-producer:
    image: strangler_fig_producer
    container_name: 'strangler_fig_producer'
    restart: on-failure
    build: 
      context: ./strangler_fig_producer
      dockerfile: ./Dockerfile
    ports: 
      - 9090:9090
    environment:
      - PAYROLL_TOPIC=payroll-v2-topic
      - INVOICING_TOPIC=invoicing-v2-topic
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - CONSUMER_GROUP_ID=payment-service-group
    networks:
      - app-network

networks:
  app-network:
    external: false