version: '3.9'
services: 

  nginx:
    image: nginx:1.21.3
    ports:
      - "80:80"
    volumes:
      - ./2_config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge