version: '3.9'
services: 

  2-parallel-run-monolith:
    image: 2_parallel_run_monolith
    container_name: '2_parallel_run_monolith'
    restart: on-failure
    build: 
      context: ./2_parallel_run_monolith
      dockerfile: ./Dockerfile
    ports: 
      - 8083:8083
    networks:
      - app-network
    environment:
      - USER_NOTIFICATION_MS_HOST=2-parallel-run-notification-ms
      - USER_NOTIFICATION_MS_PORT=8084
    depends_on: 
      - 2-parallel-run-notification-ms

  2-parallel-run-notification-ms:
    image: 2_parallel_run_notification_ms
    container_name: '2_parallel_run_notification_ms'
    restart: on-failure
    build: 
      context: ./2_parallel_run_notification_ms
      dockerfile: ./Dockerfile
    ports: 
      - 8084:8084
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge