version: '3.9'
services: 

  nginx-load-balancer:
    image: nginx:1.21.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx_10_90.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - 1-parallel-run-monolith
    networks:
      - app-network

networks:
  app-network:
    driver: bridge