version: '3.9'
services: 
  1-decorating-collaborator-monolith:
    image: 1_decorating_collaborator_monolith
    container_name: 'example_1_step_1_decorating_collaborator_monolith'
    restart: on-failure
    build: 
      context: ./1_decorating_collaborator_monolith
      dockerfile: ./Dockerfile
    ports: 
      - 8080:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge