version: '3.9'
services: 

  postgres-monolith-database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=monolith-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    restart: on-failure
    networks:
      - app-network
      
  postgres-ms-dababase:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ms-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    restart: on-failure
    networks:
      - app-network

  2-parallel-run-monolith:
    image: 2_parallel_run_monolith
    container_name: '2_parallel_run_monolith'
    restart: on-failure
    build: 
      context: ./2_parallel_run_monolith
      dockerfile: ./Dockerfile
    ports: 
      - 8082:8080
    networks:
      - app-network
    environment:
      - DATABASE_HOST=postgres-monolith-database
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASS=password
      - DATABASE_DB=monolith-db
      - USER_NOTIFICATION_MS_HOST=2-parallel-run-notification-ms
      - USER_NOTIFICATION_MS_PORT=8081
    depends_on: 
      - 2-parallel-run-notification-ms

  2-parallel-run-notification-ms:
    image: 2_parallel_run_notification_ms
    container_name: '2_parallel_run_notification_ms'
    restart: on-failure
    build: 
      context: ./2_parallel_run_notification_ms
      dockerfile: ./Dockerfile
    ports: 
      - 8081:8081
    environment:
      - DATABASE_HOST=postgres-ms-dababase
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASS=password
      - DATABASE_DB=ms-db
    depends_on:
      - postgres-ms-dababase
    networks:
      - app-network
    
  2-parallel-run-batch-service:
    image: 2_parallel_run_batch_service
    container_name: '2_parallel_run_batch_service'
    restart: on-failure
    build: 
      context: ./2_parallel_run_batch_service
      dockerfile: ./Dockerfile
    ports: 
      - 8083:8083
    environment:
      - DATABASE_MS_HOST=postgres-ms-dababase
      - DATABASE_MS_PORT=5432
      - DATABASE_MS_USER=user
      - DATABASE_MS_PASS=password
      - DATABASE_MS_DB=ms-db
      - DATABASE_MONOLITH_HOST=postgres-monolith-database
      - DATABASE_MONOLITH_PORT=5432
      - DATABASE_MONOLITH_USER=user
      - DATABASE_MONOLITH_PASS=password
      - DATABASE_MONOLITH_DB=monolith-db
    depends_on:
      - 2-parallel-run-monolith
    networks:
      - app-network
networks:
  app-network:
    driver: bridge