version: "3.9"
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    restart: always
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    restart: always
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - 9100:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - JVM_OPTS=-Xms128M -Xmx256M
    depends_on:
      - kafka

  postgres:
    build: ./postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=loyalty_data
  
  connect:
    image: debezium/connect-jdbc-es:${DEBEZIUM_VERSION}
    restart: always
    build:
      context: debezium-synch
    ports:
      - 8083:8083
      - 5005:5005
    links:
      - kafka
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=pg_synch_configs
      - OFFSET_STORAGE_TOPIC=pg_synch_offsets
      - STATUS_STORAGE_TOPIC=pg_synch_connect_statuses