version: '3.9'
services: 

  3-branch-by-abstraction-monolith:
    image: 3_branch_by_abstraction_monolith
    container_name: 'example_1_step_3_branch_by_abstraction_monolith'
    restart: on-failure
    build: 
      context: ./3_branch_by_abstraction_monolith
      dockerfile: ./Dockerfile
    ports: 
      - 8080:8080
    networks:
      - app-network
    environment:
      - USER_NOTIFICATION_MS_HOST=2-branch-by-abstraction-notification-ms
      - USER_NOTIFICATION_MS_PORT=8081

networks:
  app-network:
    driver: bridge