version: '3.9'
services: 
  1-strangler-fig-monolith:
    image: 1_strangler_fig_monolith
    container_name: '1_strangler_fig_monolith'
    restart: on-failure
    build: 
      context: ./1_strangler_fig_monolith
      dockerfile: ./Dockerfile
    ports: 
      - 8080:8080
    networks:
      - app-network
    environment:
      - VIRTUAL_HOST=payment.service
      - VIRTUAL_PORT=8080

networks:
  app-network:
    external: false