version: '3.9'

services:
  zookeeper:
    image: debezium/zookeeper:1.2
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - app-network
  
  kafka:
    image: debezium/kafka:1.2
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_CREATE_TOPICS=payroll-v1-topic:1:1,invoicing-v1-topic:1:1
    networks:
      - app-network


networks:
  app-network:
    driver: bridge