version: '3.9'

services:
  zookeeper:
    image: debezium/zookeeper:1.2
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - app-network
  
  kafka:
    image: debezium/kafka:1.2
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_CREATE_TOPICS=payroll-v1-topic:1:1,invoicing-v1-topic:1:1
    networks:
      - app-network

  1-strangler-fig-monolith:
    image: 1_strangler_fig_monolith
    container_name: 'example_3_step_1_strangler_fig_monolith'
    restart: on-failure
    build: 
      context: ./1_strangler_fig_monolith
      dockerfile: ./Dockerfile
    ports: 
      - 8080:8080
    networks:
      - app-network
    environment:
      - PAYROLL_TOPIC=payroll-v1-topic
      - INVOICING_TOPIC=invoicing-v1-topic
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - CONSUMER_GROUP_ID=payment-service-group
    depends_on: 
      - kafka


networks:
  app-network:
    driver: bridge